# -*- coding: utf-8 -*-
"""Day 3(Snowflake) .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dPp1sM8g8yB2N6ReQVUhBYYKqrMATkuE

1.reading last n lines in a file
"""

from google.colab import files
uploaded = files.upload()

def read_last_n_lines(filename, n):
    with open(filename, 'r') as f:
        lines = f.readlines()
        return lines[-n:]

# Example usage
filename = 'assignment.txt'
n = 5
last_lines = read_last_n_lines(filename, n)
print("Last", n, "lines:")
print(''.join(last_lines))

"""2. create a list by reading line by line from a file"""

from google.colab import files
uploaded = files.upload()

def file_to_list(file_name):
    lines_list = []
    with open(file_name, 'r') as f:
        for line in f:
            lines_list.append(line.strip())
    return lines_list

lines_list = file_to_list('assignment.txt')
print(lines_list)

"""3. count number of lines in the given file"""

from google.colab import files
uploaded = files.upload()

def count_lines(file_name):
    with open(file_name, 'r') as f:
        return sum(1 for _ in f)

num_lines = count_lines('assignment.txt')
print(f"Number of lines in the file: {num_lines}")

"""4. find the lengthy words in a given file."""

from google.colab import files
uploaded = files.upload()

def find_lengthy_words(file_name, length=7):
    lengthy_words = []
    with open(file_name, 'r') as f:
        for line in f:
            words = line.strip().split()
            lengthy_words.extend([word for word in words if len(word) > length])
    return lengthy_words

long_words = find_lengthy_words('assignment.txt', length=7)
print("Lengthy words (more than 7 letters):")
print(long_words)