# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HRAIELoDLTH7SpR1_0xKKcYKA4oh72Rr
"""

#Student Performance Analysis

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


sns.set(style="whitegrid")

#Synthetic Dataset
num_students = 100

data = {
    'Student_ID': range(1, num_students + 1),
    'Gender': np.random.choice(['Male', 'Female'], size=num_students),
    'Age': np.random.randint(14, 20, size=num_students),
    'Study_Hours': np.round(np.random.normal(3.5, 1.2, num_students), 1),
    'Attendance_%': np.round(np.random.normal(85, 10, num_students), 1),
    'Parental_Education': np.random.choice(['High School', 'Graduate', 'Post Graduate'], size=num_students),
    'Sports_Participation': np.random.choice(['Yes', 'No'], size=num_students),
    'Math_Score': np.random.randint(30, 100, size=num_students),
    'Reading_Score': np.random.randint(35, 100, size=num_students),
    'Writing_Score': np.random.randint(40, 100, size=num_students),
}

df = pd.DataFrame(data)

#Basic Data Inspection
print("📘 First 5 Rows of Data:")
print(df.head())

print("\n📋 Dataset Information:")
print(df.info())

print("\n📊 Summary Statistics:")
print(df.describe())

df['Average_Score'] = df[['Math_Score', 'Reading_Score', 'Writing_Score']].mean(axis=1)

#Study Hours vs Average Score
plt.figure(figsize=(8, 5))
sns.scatterplot(data=df, x='Study_Hours', y='Average_Score', color='blue')
plt.title("Study Hours vs Average Score")
plt.xlabel("Study Hours per Day")
plt.ylabel("Average Score")
plt.show()

#Attendance vs Average Score
plt.figure(figsize=(8, 5))
sns.scatterplot(data=df, x='Attendance_%', y='Average_Score', color='green')
plt.title("Attendance vs Average Score")
plt.xlabel("Attendance (%)")
plt.ylabel("Average Score")
plt.show()

#Average Score by Parental Education
plt.figure(figsize=(8, 5))
sns.barplot(data=df, x='Parental_Education', y='Average_Score', hue='Parental_Education',
            palette='Set2', legend=False)
plt.title("Average Score by Parental Education Level")
plt.xlabel("Parental Education Level")
plt.ylabel("Average Score")
plt.show()


#Average Performance by Gender
plt.figure(figsize=(8, 5))
sns.barplot(data=df, x='Gender', y='Average_Score', hue='Gender',
            palette='pastel', legend=False)
plt.title("Average Performance by Gender")
plt.xlabel("Gender")
plt.ylabel("Average Score")
plt.show()