# -*- coding: utf-8 -*-
"""A2_15-10-2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fJMfsfxRqr0_4ww29mr7M_mAADVl64JC
"""

#reading last n lines
def read_last_n_lines(filename='sample.txt', n=3):
    with open(filename, 'r') as file:
        lines = file.readlines()
        return lines[-n:]
last_lines = read_last_n_lines(filename, n)
for line in last_lines:
    print(line, end='')

#reading line by line
def read_lines_as_list(filename='sample.txt'):
    result = []
    with open(filename, 'r') as file:
        for line in file:
            result.append(line.rstrip('\n'))
    return result
lines_list = read_lines_as_list(filename)
print(lines_list)

#count no of lines
def count_lines(filename='sample.txt'):
    with open(filename, 'r') as f:
        return sum(1 for _ in f)
print("Number of lines:", count_lines(filename))

#find lengthy words
def find_lengthy_words(filename='sample.txt', min_length=5):
    lengthy_words = set()
    with open(filename, 'r') as f:
        words = f.read().split()
        for word in words:
            if len(word) >= min_length:
                lengthy_words.add(word)
    return list(lengthy_words)
print(find_lengthy_words(filename, 5))