# -*- coding: utf-8 -*-
"""A3_16-10-2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mty67v1tNMDPysYw28S8SISaveM4t2QA
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set random seed for reproducibility
np.random.seed(42)
num_students = 200

# Generate synthetic data
data = {
    'Student_ID': range(1, num_students + 1),
    'Gender': np.random.choice(['Male', 'Female'], size=num_students),
    'Age': np.random.randint(14, 20, size=num_students),
    'Study_Hours': np.round(np.random.normal(3.5, 1.2, num_students), 1),
    'Attendance_%': np.round(np.random.normal(85, 10, num_students), 1),
    'Parental_Education': np.random.choice(['High School', 'Graduate', 'Post Graduate'], size=num_students),
    'Sports_Participation': np.random.choice(['Yes', 'No'], size=num_students),
    'Math_Score': np.random.randint(30, 100, size=num_students),
    'Reading_Score': np.random.randint(35, 100, size=num_students),
    'Writing_Score': np.random.randint(40, 100, size=num_students),
}

df = pd.DataFrame(data)
df['Average_Score'] = df[['Math_Score', 'Reading_Score', 'Writing_Score']].mean(axis=1)

#Basic Data Inspection

print(df.info())
print(df.head())
print(df.describe())

#Visualisation: Study Hours vs Average Score

plt.figure(figsize=(8, 5))
sns.scatterplot(x='Study_Hours', y='Average_Score', data=df, hue='Gender', style='Gender')
plt.title('Study Hours vs Average Score')
plt.savefig('study_hours_vs_avg_score.png')
plt.show()

#Visualisation: Attendance vs Average Score

plt.figure(figsize=(8, 5))
sns.scatterplot(x='Attendance_%', y='Average_Score', data=df, hue='Gender', style='Gender')
plt.title('Attendance % vs Average Score')
plt.savefig('attendance_vs_avg_score.png')
plt.show()

#Average Score by Parental Education Level

plt.figure(figsize=(7, 5))
sns.barplot(x='Parental_Education', y='Average_Score', data=df, ci=None)
plt.title('Average Score by Parental Education Level')
plt.savefig('avg_score_parent_edu.png')
plt.show()

#Average Performance by Gender

plt.figure(figsize=(6,4))
sns.barplot(x='Gender', y='Average_Score', data=df, ci=None)
plt.title('Average Performance by Gender')
plt.savefig('avg_score_by_gender.png')
plt.show()